### ISSUE TITLE
Multiplication between matrix of different size

### ISSUE THREAD

**Issue by stebogit** [raghavgujjar/matrix#2]
@raghavgujjar I noticed this issue:

```javascript
var A = matrix([
    [1, 2, 3],
    [4, 5, 6]
]);
var B = matrix([
    [7, 8],
    [9, 10],
    [11, 12]
]);
A.prod(B); //= [[58, 64, null],[139, 154, null]]
// instead of [[58, 64],[139, 154]]
```
I'll send you a PR with the simple fix, if you like to merge it.

**Comment by raghavgujjar** [comment]
@stebogit thank you for the fix. I don't have a CI. I will verify your fix and merge it.

**Comment by raghavgujjar** [comment]
The fix is merged. Closing the issue.

**Comment by NotoriousWebmaster** [comment]
Please specify in the documentation that mul() is NOT matrix multiplication! I'm working on 2D transformation matrices, and when I multiply a 3x3 with a 3x1, I get 3 results and 6 NaN. No bueno. Mui, no bueno.

My recommendation would be to throw an error if you try to mul() two matrices of different sizes. And the error could explain that maybe the user wants to use the prod() method.

But also, document it in the documentation.

Thank you.
