### ISSUE TITLE
inv() calculation is not correct in some cases

### ISSUE THREAD

**Issue by tianzjyh** [raghavgujjar/matrix#7]
First construct a matrix with an array:
`var A = matrix([[0,1,0],[0,0,1],[1,1,1]]);`
Then calculate its inverse matrix:
`var B = A.inv()`
The calculation result of B is [[1,2,-1],[1,0,0],[-1,-1,1]], but it is expected to be [[-1,-1,1],[1,0,0],[0,1,0]]

Tested with the matrix-js npm package, version 1.6.0(latest by now).

**Comment by dantecsm** [comment]
another case
![image](https://user-images.githubusercontent.com/35835538/147429818-5feaf984-4029-4f41-9b80-8eeb89392785.png)

**Comment by raghavgujjar** [comment]
Fixed with this commit: https://github.com/raghavgujjar/matrix/commit/4640e22210d04c43e8f127dab285d3b9c1b8f2b5
